DROP TABLE IF EXISTS Volunteer;

CREATE TABLE Volunteer (
    id INTEGER PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(255) NOT NULL,
    cpf VARCHAR(255) NOT NULL UNIQUE,
    is_active BOOLEAN NOT NULL
);
